package org.iu.chess.move;

public enum MoveRequirement {
  NONE,
  REQUIRES_PIECE_AT_TARGET_SQUARE,
  REQUIRES_EMPTY_TARGET_SQUARE,
  REQUIRES_EMPTY_RANK,
  REQUIRES_EMPTY_FILE,
  REQUIRES_EMPTY_DIAGONAL,
  REQUIRES_NO_MUTUAL_PIECE_AT_TARGET_SQUARE,
  PIECE_NEVER_MOVED,
  CASTLING,
}
